// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4QEH90TdcHckG75j-MsNrbN9mNZB-NRw',
    appId: '1:880682586902:web:f1e35332b3c782139bf637',
    messagingSenderId: '880682586902',
    projectId: 'e-commercial-ed80e',
    authDomain: 'e-commercial-ed80e.firebaseapp.com',
    storageBucket: 'e-commercial-ed80e.appspot.com',
    measurementId: 'G-KBLBZ34K87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtu9_dIPZPAsVmzj4HeteX0hCfTKidAKk',
    appId: '1:880682586902:android:be02e7890265a9529bf637',
    messagingSenderId: '880682586902',
    projectId: 'e-commercial-ed80e',
    storageBucket: 'e-commercial-ed80e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_dH8FkPQkXZGbUc8zJvE942zGcajq2g8',
    appId: '1:880682586902:ios:9b93e5f5ceedd06b9bf637',
    messagingSenderId: '880682586902',
    projectId: 'e-commercial-ed80e',
    storageBucket: 'e-commercial-ed80e.appspot.com',
    iosBundleId: 'com.example.ecommracApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_dH8FkPQkXZGbUc8zJvE942zGcajq2g8',
    appId: '1:880682586902:ios:76157b8880a970139bf637',
    messagingSenderId: '880682586902',
    projectId: 'e-commercial-ed80e',
    storageBucket: 'e-commercial-ed80e.appspot.com',
    iosBundleId: 'com.example.ecommracApp.RunnerTests',
  );
}
